apiVersion: batch/v1
kind: Job
metadata:
  name: app-migrate-job
spec:
  template:
    spec:
      containers:
        - name: app-migrate-job
          image: ${IMAGE}
          command: ['bin/rails']
          args: ['db:migrate']
          env:
            - name: RAILS_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: rails_master_key
            - name: RAILS_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RAILS_ENV
      volumes:
        - name: secret-volume
          secret:
            secretName: app-secret
      restartPolicy: Never
  backoffLimit: 4
